### ISSUE TITLE
Load Gallery Image Automatically Zoom

### ISSUE THREAD

**Issue by ArslanKathia** [IsseiAoki/SimpleCropView#77]
when i load the image from gallery it's automatically zoom ??
Any Solution?

**Comment by hexianqiao3755** [comment]
@ArslanKathia  hey, guy! i meet this problem too.  how you is solved this problem?

**Comment by ArslanKathia** [comment]
i try my best but problem remain constant i didn't find any thing that zoom
the image.....

**Comment by hexianqiao3755** [comment]
@ArslanKathia me too, but i find a better , have image zoom method.
[https://github.com/Yalantis/uCrop](url)
